service: nodeless # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: 'us-east-1'
  
functions:
  entrada_fila:
    handler: lambda1.handle
    environment:
      bucket: rocketnodeserverless
    memorySize: 128
    description: Submit candidate information and starts interview process.
    events:
      - http: 
          path: filaSqs
          method: post